// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm2zpQqQ0F-Z36ieijIOoM_6AhPJG6eZc',
    appId: '1:1002599316466:web:5ec8e428cb77341184496b',
    messagingSenderId: '1002599316466',
    projectId: 'insta-ui-30961',
    authDomain: 'insta-ui-30961.firebaseapp.com',
    storageBucket: 'insta-ui-30961.firebasestorage.app',
    measurementId: 'G-1HH50HS3FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc9LdNtsfMMZRbFoTYVo3iOayKE6Kn-p8',
    appId: '1:1002599316466:android:ffb73160b1f69eb284496b',
    messagingSenderId: '1002599316466',
    projectId: 'insta-ui-30961',
    storageBucket: 'insta-ui-30961.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIqpyeOEHSg0c--XzHqRSXhM9s1nJNvsM',
    appId: '1:1002599316466:ios:111f368085bb2e1c84496b',
    messagingSenderId: '1002599316466',
    projectId: 'insta-ui-30961',
    storageBucket: 'insta-ui-30961.firebasestorage.app',
    iosBundleId: 'com.example.instaUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIqpyeOEHSg0c--XzHqRSXhM9s1nJNvsM',
    appId: '1:1002599316466:ios:111f368085bb2e1c84496b',
    messagingSenderId: '1002599316466',
    projectId: 'insta-ui-30961',
    storageBucket: 'insta-ui-30961.firebasestorage.app',
    iosBundleId: 'com.example.instaUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCm2zpQqQ0F-Z36ieijIOoM_6AhPJG6eZc',
    appId: '1:1002599316466:web:fe3486cbda7dd3dd84496b',
    messagingSenderId: '1002599316466',
    projectId: 'insta-ui-30961',
    authDomain: 'insta-ui-30961.firebaseapp.com',
    storageBucket: 'insta-ui-30961.firebasestorage.app',
    measurementId: 'G-TL67JHXV5E',
  );

}